### ISSUE TITLE
Where's 1.0 version for this element?

### ISSUE THREAD

**Issue by Mygod** [Polymer/core-tooltip#35] opened 2015-05-30 09:21 UTC
There's neither `iron-tooltip` nor `paper-tooltip`. Does this mean I should probably go back to using `title` attribute? :cry:

**Comment by ebidel** [comment] 2015-05-31 02:05
This one was low priority for the initial release, but we'll definitely get something out in the coming weeks.

**Comment by eximius313** [comment] 2015-06-09 20:14
+1

**Comment by Pickachu** [comment] 2015-06-11 20:17
:+1:

**Comment by jhou-pro** [comment] 2015-06-15 07:32
+1

**Comment by exload** [comment] 2015-06-15 21:57
+1

**Comment by sansantosh** [comment] 2015-06-16 02:39
+1

**Comment by pshihn** [comment] 2015-06-16 03:52
+1

**Comment by luccamordente** [comment] 2015-06-18 09:54
+1

**Comment by ValueBC** [comment] 2015-06-18 15:52
+1

**Comment by shkate** [comment] 2015-06-24 13:08
+1

**Comment by kiryaka** [comment] 2015-06-24 23:00
+1

**Comment by avm99963** [comment] 2015-07-02 15:54
+1

**Comment by M0nter0** [comment] 2015-07-07 06:18
The element is "in progress" as you can see in the road-map for paper elements.
https://github.com/PolymerElements/paper-elements

**Comment by notwaldorf** [comment] 2015-07-07 15:16
Closing this, as it's technically a duplicate of https://github.com/PolymerElements/paper-elements/issues/18. I have a PR out for `paper-tooltip`, and it should be ready hopefully by next week.

**Closed by notwaldorf** 2015-07-07 15:16 UTC

**Comment by Mygod** [comment] 2015-07-12 06:25
A temporary workaround for people who are immigrating from 0.5:

    <dom-module id="paper-tooltip">
        <script>
            Polymer({
                is: "paper-tooltip",
                ready: function () {
                    var tip = this.querySelector("[tip]");
                    this.setAttribute("title", tip.innerText);
                    tip.remove();
                }
            });
        </script>
    </dom-module>

**Comment by Sinjins** [comment] 2015-07-13 19:53
+1

**Comment by notwaldorf** [comment] 2015-07-14 02:06
:wave: Here it is: https://github.com/PolymerElements/paper-tooltip. 😊
